// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Cars.proto

package cars

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Car struct {
	Model                   string   `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	BrandName               string   `protobuf:"bytes,2,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	BrandCreatorCountry     string   `protobuf:"bytes,3,opt,name=brand_creator_country,json=brandCreatorCountry,proto3" json:"brand_creator_country,omitempty"`
	EngineModel             string   `protobuf:"bytes,4,opt,name=engine_model,json=engineModel,proto3" json:"engine_model,omitempty"`
	EnginePower             int32    `protobuf:"varint,5,opt,name=engine_power,json=enginePower,proto3" json:"engine_power,omitempty"`
	EngineVolume            int32    `protobuf:"varint,6,opt,name=engine_volume,json=engineVolume,proto3" json:"engine_volume,omitempty"`
	EngineType              string   `protobuf:"bytes,7,opt,name=engine_type,json=engineType,proto3" json:"engine_type,omitempty"`
	TransmissionModel       string   `protobuf:"bytes,8,opt,name=transmission_model,json=transmissionModel,proto3" json:"transmission_model,omitempty"`
	TransmissionType        string   `protobuf:"bytes,9,opt,name=transmission_type,json=transmissionType,proto3" json:"transmission_type,omitempty"`
	TransmissionGearsNumber int32    `protobuf:"varint,10,opt,name=transmission_gears_number,json=transmissionGearsNumber,proto3" json:"transmission_gears_number,omitempty"`
	WheelModel              string   `protobuf:"bytes,11,opt,name=wheel_model,json=wheelModel,proto3" json:"wheel_model,omitempty"`
	WheelRadius             int32    `protobuf:"varint,12,opt,name=wheel_radius,json=wheelRadius,proto3" json:"wheel_radius,omitempty"`
	WheelColor              string   `protobuf:"bytes,13,opt,name=wheel_color,json=wheelColor,proto3" json:"wheel_color,omitempty"`
	Price                   int32    `protobuf:"varint,14,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Car) Reset()         { *m = Car{} }
func (m *Car) String() string { return proto.CompactTextString(m) }
func (*Car) ProtoMessage()    {}
func (*Car) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3938f9a8ece61d3, []int{0}
}

func (m *Car) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Car.Unmarshal(m, b)
}
func (m *Car) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Car.Marshal(b, m, deterministic)
}
func (m *Car) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Car.Merge(m, src)
}
func (m *Car) XXX_Size() int {
	return xxx_messageInfo_Car.Size(m)
}
func (m *Car) XXX_DiscardUnknown() {
	xxx_messageInfo_Car.DiscardUnknown(m)
}

var xxx_messageInfo_Car proto.InternalMessageInfo

func (m *Car) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Car) GetBrandName() string {
	if m != nil {
		return m.BrandName
	}
	return ""
}

func (m *Car) GetBrandCreatorCountry() string {
	if m != nil {
		return m.BrandCreatorCountry
	}
	return ""
}

func (m *Car) GetEngineModel() string {
	if m != nil {
		return m.EngineModel
	}
	return ""
}

func (m *Car) GetEnginePower() int32 {
	if m != nil {
		return m.EnginePower
	}
	return 0
}

func (m *Car) GetEngineVolume() int32 {
	if m != nil {
		return m.EngineVolume
	}
	return 0
}

func (m *Car) GetEngineType() string {
	if m != nil {
		return m.EngineType
	}
	return ""
}

func (m *Car) GetTransmissionModel() string {
	if m != nil {
		return m.TransmissionModel
	}
	return ""
}

func (m *Car) GetTransmissionType() string {
	if m != nil {
		return m.TransmissionType
	}
	return ""
}

func (m *Car) GetTransmissionGearsNumber() int32 {
	if m != nil {
		return m.TransmissionGearsNumber
	}
	return 0
}

func (m *Car) GetWheelModel() string {
	if m != nil {
		return m.WheelModel
	}
	return ""
}

func (m *Car) GetWheelRadius() int32 {
	if m != nil {
		return m.WheelRadius
	}
	return 0
}

func (m *Car) GetWheelColor() string {
	if m != nil {
		return m.WheelColor
	}
	return ""
}

func (m *Car) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type SaveRequest struct {
	Cars                 []*Car   `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3938f9a8ece61d3, []int{1}
}

func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (m *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(m, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetCars() []*Car {
	if m != nil {
		return m.Cars
	}
	return nil
}

type SaveReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveReply) Reset()         { *m = SaveReply{} }
func (m *SaveReply) String() string { return proto.CompactTextString(m) }
func (*SaveReply) ProtoMessage()    {}
func (*SaveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3938f9a8ece61d3, []int{2}
}

func (m *SaveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveReply.Unmarshal(m, b)
}
func (m *SaveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveReply.Marshal(b, m, deterministic)
}
func (m *SaveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveReply.Merge(m, src)
}
func (m *SaveReply) XXX_Size() int {
	return xxx_messageInfo_SaveReply.Size(m)
}
func (m *SaveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveReply.DiscardUnknown(m)
}

var xxx_messageInfo_SaveReply proto.InternalMessageInfo

func (m *SaveReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Car)(nil), "cars.Car")
	proto.RegisterType((*SaveRequest)(nil), "cars.SaveRequest")
	proto.RegisterType((*SaveReply)(nil), "cars.SaveReply")
}

func init() { proto.RegisterFile("Cars.proto", fileDescriptor_b3938f9a8ece61d3) }

var fileDescriptor_b3938f9a8ece61d3 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xd1, 0x8b, 0xd3, 0x40,
	0x10, 0xc6, 0x8d, 0x6d, 0xef, 0x9a, 0xc9, 0x9d, 0x7a, 0xab, 0xe2, 0x2a, 0x1c, 0xd6, 0x8a, 0x50,
	0x50, 0x8b, 0xd4, 0x37, 0xf1, 0x2d, 0x0f, 0x3e, 0x79, 0x48, 0x14, 0x5f, 0xc3, 0x36, 0x1d, 0x6a,
	0x20, 0xd9, 0x8d, 0xb3, 0xc9, 0x1d, 0xf9, 0x23, 0xfc, 0x9f, 0x65, 0x67, 0xd2, 0x6b, 0xfa, 0x96,
	0xf9, 0xbe, 0xdf, 0xcc, 0x7c, 0x6c, 0x06, 0x20, 0x35, 0xe4, 0xd7, 0x0d, 0xb9, 0xd6, 0xa9, 0x69,
	0x61, 0xc8, 0x2f, 0xff, 0x4d, 0x61, 0x92, 0x1a, 0x52, 0xcf, 0x60, 0x56, 0xbb, 0x1d, 0x56, 0x3a,
	0x5a, 0x44, 0xab, 0x38, 0x93, 0x42, 0x5d, 0x03, 0x6c, 0xc9, 0xd8, 0x5d, 0x6e, 0x4d, 0x8d, 0xfa,
	0x21, 0x5b, 0x31, 0x2b, 0x37, 0xa6, 0x46, 0xb5, 0x81, 0xe7, 0x62, 0x17, 0x84, 0xa6, 0x75, 0x94,
	0x17, 0xae, 0xb3, 0x2d, 0xf5, 0x7a, 0xc2, 0xe4, 0x53, 0x36, 0x53, 0xf1, 0x52, 0xb1, 0xd4, 0x1b,
	0xb8, 0x40, 0xbb, 0x2f, 0x2d, 0xe6, 0xb2, 0x6f, 0xca, 0x68, 0x22, 0xda, 0x77, 0xde, 0x7a, 0x44,
	0x1a, 0x77, 0x87, 0xa4, 0x67, 0x8b, 0x68, 0x35, 0x3b, 0x20, 0x3f, 0x82, 0xa4, 0xde, 0xc2, 0xe5,
	0x80, 0xdc, 0xba, 0xaa, 0xab, 0x51, 0x9f, 0x31, 0x33, 0xf4, 0xfd, 0x66, 0x4d, 0xbd, 0x86, 0xa1,
	0x27, 0x6f, 0xfb, 0x06, 0xf5, 0x39, 0x6f, 0x02, 0x91, 0x7e, 0xf5, 0x0d, 0xaa, 0x8f, 0xa0, 0x5a,
	0x32, 0xd6, 0xd7, 0xa5, 0xf7, 0xa5, 0xb3, 0x43, 0xa2, 0x39, 0x73, 0x57, 0x63, 0x47, 0x72, 0xbd,
	0x87, 0x13, 0x51, 0xa6, 0xc6, 0x4c, 0x3f, 0x19, 0x1b, 0x3c, 0xfb, 0x0b, 0xbc, 0x3c, 0x81, 0xf7,
	0x68, 0xc8, 0xe7, 0xb6, 0xab, 0xb7, 0x48, 0x1a, 0x38, 0xed, 0x8b, 0x31, 0xf0, 0x2d, 0xf8, 0x37,
	0x6c, 0x87, 0xe0, 0x77, 0x7f, 0x10, 0xab, 0x21, 0x50, 0x22, 0xc1, 0x59, 0xba, 0x7f, 0x21, 0x01,
	0xc8, 0xec, 0xca, 0xce, 0xeb, 0x0b, 0x79, 0x21, 0xd6, 0x32, 0x96, 0x8e, 0x33, 0x0a, 0x57, 0x39,
	0xd2, 0x97, 0xa3, 0x19, 0x69, 0x50, 0xc2, 0x1f, 0x6f, 0xa8, 0x2c, 0x50, 0x3f, 0xe2, 0x66, 0x29,
	0x96, 0x1f, 0x20, 0xf9, 0x69, 0x6e, 0x31, 0xc3, 0xbf, 0x1d, 0xfa, 0x56, 0x5d, 0x03, 0x9f, 0x89,
	0x8e, 0x16, 0x93, 0x55, 0xb2, 0x89, 0xd7, 0xa1, 0x58, 0xa7, 0x86, 0x32, 0xb9, 0x9e, 0x77, 0x10,
	0x0b, 0xdd, 0x54, 0xbd, 0xd2, 0x70, 0x5e, 0xa3, 0xf7, 0x66, 0x8f, 0xc3, 0x11, 0x1d, 0xca, 0xcd,
	0x57, 0x98, 0xa7, 0x86, 0x02, 0x49, 0xea, 0x13, 0xcc, 0xc3, 0x47, 0x38, 0x44, 0x75, 0x25, 0xf3,
	0x46, 0x0b, 0x5f, 0x3d, 0x1e, 0x4b, 0x4d, 0xd5, 0x2f, 0x1f, 0x6c, 0xcf, 0xf8, 0x5e, 0x3f, 0xff,
	0x0f, 0x00, 0x00, 0xff, 0xff, 0x17, 0xf9, 0x63, 0x75, 0xbd, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CarSaverClient is the client API for CarSaver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CarSaverClient interface {
	SaveCars(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveReply, error)
}

type carSaverClient struct {
	cc *grpc.ClientConn
}

func NewCarSaverClient(cc *grpc.ClientConn) CarSaverClient {
	return &carSaverClient{cc}
}

func (c *carSaverClient) SaveCars(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, "/cars.CarSaver/SaveCars", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarSaverServer is the server API for CarSaver service.
type CarSaverServer interface {
	SaveCars(context.Context, *SaveRequest) (*SaveReply, error)
}

// UnimplementedCarSaverServer can be embedded to have forward compatible implementations.
type UnimplementedCarSaverServer struct {
}

func (*UnimplementedCarSaverServer) SaveCars(ctx context.Context, req *SaveRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveCars not implemented")
}

func RegisterCarSaverServer(s *grpc.Server, srv CarSaverServer) {
	s.RegisterService(&_CarSaver_serviceDesc, srv)
}

func _CarSaver_SaveCars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarSaverServer).SaveCars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cars.CarSaver/SaveCars",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarSaverServer).SaveCars(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CarSaver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cars.CarSaver",
	HandlerType: (*CarSaverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveCars",
			Handler:    _CarSaver_SaveCars_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Cars.proto",
}
